---
# Install Packages
- name: Check if running first time
  stat:
    path: "{{ first_run_loc_file }}"
  register: first_run_file

- name: First run tasks
  block:
   - name: apt upgrade on first run
     apt:
       update_cache: yes
       upgrade: full
       cache_valid_time: 86400
   - name: Create first_run_loc_file
     file:
       path: "{{ first_run_loc_file }}"
       state: touch
       owner: root
       group: root
       mode: '0644'
   - name: Check if reboot is required
     stat:
       path: "{{ reboot_required_file }}"
     register: reboot_required_file
   - name: Reboot server
     reboot:
       msg: "Reboot initiated by Ansible to complete system upgrade"
     when: reboot_required_file.stat.exists
  when: not first_run_file.stat.exists

- name: Install required system packages
  apt: name={{ required_packages }} state=latest update_cache=yes
  tags: skip_ansible_lint

- name: Install python 3 libraries
  pip:
    state: latest
    name: "{{ python3_modules }}"
  tags: skip_ansible_lint
