---
- name: "Create required directories for letsencrypt"
  file:
    path: "/etc/letsencrypt/{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    mode: u=rwx,g=x,o=x
  with_items:
    - account
    - certs
    - csrs
    - keys

- name: Download options-ssl-nginx.conf
  get_url:
    url: https://raw.githubusercontent.com/certbot/certbot/master/certbot-nginx/certbot_nginx/_internal/tls_configs/options-ssl-nginx.conf
    dest: /etc/letsencrypt/options-ssl-nginx.conf
    owner: www-data
    group: www-data
    mode: u=rw,g=r,o=r
  notify: Reload NGINX Configuration

- name: Upload NGINX vhost config files
  template:
    src: letsencrypt.conf.j2
    dest: "{{ nginx_vhost_path }}/letsencrypt.conf"
    force: true
    owner: www-data
    group: www-data
    mode: "0644"
  notify: Reload NGINX Configuration
