---
- name: Upload NGINX vhost config files
  template:
    src: letsencrypt.conf.j2
    dest: "{{ nginx_vhost_path }}/letsencrypt.conf"
    force: true
    owner: www-data
    group: www-data
    mode: "0644"
  notify: Reload NGINX Configuration

- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers

- name: Temporary allow incoming http connections for letsencrypt (handler to block access after)
  ufw:
    rule: allow
    proto: tcp
    to_port: "80"
    comment: Allow incoming http connections for letsencrypt
  notify: Block incoming http connections for letsencrypt
