---
- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers

- name: Ensure nginx service is running as configured
  service:
    name: nginx
    state: started
    enabled: true
