---
- hosts: all
  gather_facts: false
  vars:
    - ansible_ssh_private_key_file: !!null
  vars_prompt:
    - name: "ansible_ssh_user"
      prompt: "Remote user"
    - name: "ansible_ssh_pass"
      prompt: "Remote user password"
      unsafe: yes
      private: yes
  become: yes
  become_user: root

  tasks:
    - name: Set ansible_ssh_pass variable
      set_fact:
        ansible_sudo_pass: "{{ ansible_ssh_pass }}"

    - name: Get fingerprint for host
      shell: ssh-keyscan -t rsa "{{ inventory_hostname }}"
      delegate_to: localhost
      register: ssh_key
      tags: skip_ansible_lint

    - name: Add fingerprint to known_hosts
      delegate_to: localhost
      known_hosts:
        name: "{{ inventory_hostname }}"
        key: "{{ ssh_key.stdout }} "
        hash_host: yes
        state: present

    - import_role:
        name: common
        tasks_from: credentials
      vars:
