---
- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers

- name: Ensure uWSGI service is running as configured
  systemd:
    name: emperor.uwsgi
    enabled: yes
    state: started
    masked: no
